localstack_endpoint            = ""
lambda_aws_endpoint_url        = ""
environment                    = "production"
aws_region                     = "us-east-1"
aws_account_id                 = "111111111111" # replace before promotion
resource_prefix                = "f2e"
kms_key_arn                    = "arn:aws:kms:us-east-1:111111111111:key/00000000-0000-0000-0000-000000000000" # replace
lambda_zip_dir                 = "../.build"
lambda_runtime                 = "provided.al2023"
lambda_timeout                 = 60
lambda_memory_mb               = 1024
organizer_reserved_concurrency = 2
worker_reserved_concurrency    = 20
worker_maximum_concurrency     = 20
worker_batch_size              = 1
f2e_input_bucket               = "replace-me-f2e-production"
sqs_visibility_timeout         = 1800
sqs_max_receive_count          = 3
log_retention_days             = 90
