services:
  localstack:
    image: localstack/localstack:3.8.1
    container_name: localstack-main
    hostname: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,lambda,logs,iam
      - SQS_ENDPOINT_STRATEGY=path
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=automacao_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh:ro
      - ../.build:/opt/f2e:ro
